### PR TITLE
Update automatic "Python" labeler

### PR DESCRIPTION
**Pull request by eriknw**
Triggered by changes to `nx_cugraph/` and `_nx_cugraph`.

Is this label still useful to us or to ops?

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Giving you a `ci-codeowners` approval. Up to you if you want to use this. My opinion... now that this is in its own repo, and since it doesn't have a C++ component, I don't think a separate `python` label is that valuable.

**Comment by eriknw** [comment]
Thanks. Yeah, I don't have an opinion one way or another. I suppose it would be nicer to have one less label to choose from when assigning labels manually.

**Comment by eriknw** [comment]
Alternative that removes it (for when we decide what to do): https://github.com/rapidsai/nx-cugraph/pull/23

**Comment by eriknw** [comment]
Closing in favor of #23 (for now)

**Pull request closed without merging**
