### PR TITLE
add devcontainers

### PR DESCRIPTION
**Pull request by jameslamb**
Adds devcontainers and devcontainer CI jobs.

## Notes for Reviewers

I created this by copying from the `cugraph` repo and then just changing all the references to `nx-cugraph` (and removing a few unnecessary things, like details about cloning cugraph-ops).

This will be blocked until https://github.com/rapidsai/devcontainers/pull/417 or https://github.com/rapidsai/devcontainers/pull/418 is merged.

### CODE REVIEW

**Comment by jameslamb** [comment]
Cancelled CI to save those resources for other projects.

@eriknw , restart CI here once https://github.com/rapidsai/devcontainers/pull/417 or https://github.com/rapidsai/devcontainers/pull/418 is merged.

**Review by eriknw — APPROVED** [review]
LGTM insofar as I can tell :+1:

**Review by trxcllnt — APPROVED** [review]
LGTM :+1:

**Review by nv-rliu — APPROVED** [review]

**Comment by nv-rliu** [comment]
Merging now that https://github.com/rapidsai/devcontainers/pull/417 and https://github.com/rapidsai/devcontainers/pull/418 have been merged.

**Review by bdice — APPROVED** [review]

**Pull request merged**
